---
title: "Spatial autocorrelation analysis"
author: "Inga Kartozia"
date: "18 05 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Mapping number of genders
``` {r message=FALSE, }
library(tidyverse)
library(lingtypology)
df <- read.csv("https://raw.githubusercontent.com/kartozia/spatial_analysis_of_NakhDaghestanian_languages/master/data/allvillages_v2.csv", sep = ";")
df <- as_tibble(df)

map.feature(languages = df$Language,
            latitude = as.numeric(df$Lat),
            longitude = as.numeric(df$Lon),
            features = df$classes,
            label = paste(df$Language, df$dialect),
            popup = df$EngNames,
            tile = 'CartoDB.Positron',
            color = "viridis",
            width = 3, stroke.radius = 3)

```

### Creating a weight matrix
```{r warning=FALSE, message=FALSE}
library(spdep)
sp_df <- df[,c(2,3,4,9,12,13)]
sp_df <- unique(sp_df)
sp_df[is.na(sp_df)] <- 0
space <- cbind(as.numeric(sp_df$Lon), as.numeric(sp_df$Lat))
test <- knn2nb(knearneigh(space, k=5, longlat = TRUE), row.names = sp_df$index)
final <- include.self(test)
ww <- nb2listw(final, style='B', zero.policy = TRUE)
```

### Calculating Moran's I
``` {r}
moran.test(sp_df$classes, ww,randomisation=FALSE) # Moran's I and significance test
moran.mc(sp_df$classes, ww, nsim=99) # Monte Carlo simulation
```


### Calculating and mapping Getis and Ord Gi
``` {r}
localGvalues <- localG(x = as.numeric(sp_df$classes), listw = ww, zero.policy = TRUE)
localGvalues <- round(localGvalues,3)
sp_df$values <- localGvalues
sp_df <- sp_df[,-1]
#globalG.test(sp_df$classes, ww)
map.feature(languages = sp_df$Language,
            latitude = as.numeric(sp_df$Lat),
            longitude = as.numeric(sp_df$Lon),
            features = as.numeric(sp_df$values),
            label = paste(sp_df$Language,sp_df$classes),
            popup = sp_df$EngNames,
            tile = 'CartoDB.Positron',
            color= "viridis",
            width = 3.5, stroke.radius = 3)
```